### ISSUE TITLE
404 error on saving and deleting name

### ISSUE THREAD

**Issue by Crackerhead22** [GoryMoon/SubscriptionWhitelist#1]
I'm getting the "No Minecraft name found for this username" error, so I went to delete or change the username, getting a 404 error `https://whitelist.gorymoon.se/function%20()%20%7B%20[native%20code]%20%7D`  on each.

Did this on Android Chrome in desktop mode.

**Comment by Crackerhead22** [comment]
Just out of curiosity, why am I getting "No Minecraft name found for this username" ?  My Minecraft username is spelled correctly.

**Comment by GoryMoon** [comment]
Oh, sorry have missed that this got reported.
Will look into it shortly.

**Comment by GoryMoon** [comment]
Should be fixed now, give it a try to change the name to something else and then back.
