### ISSUE TITLE
Violates the following Content Security Policy directive.  None of the form submits work because of that.

### ISSUE THREAD

**Issue by BenLeclerc** [GoryMoon/SubscriptionWhitelist#15]
Getting an error when trying to click on links on the subscriber dashboard.  Console says "Refused to send form data to 'http://whitelist.gorymoon.se/subscriber/mhykol/steam' because it violates the following Content Security Policy directive: "form-action 'self'"."

The steps that caused this.  The order is likely a little mixed on steps, as I (Twitch: RoboticBen) was trying a lot.  I was blocked logging into Eco because my subscription (Darkosto gift sub) expired.  I renewed my subscription, but nothing was happening.  I later announced my subscription to the channel, hoping that would help, but it didn't.  I cleared cookies occasionally during this to help, it did not.  I realized that I had another subscription (Mhykol gift sub), so I added that.  I unlinked my Steam Account.

Eventually, it got to a state where I was on the subscriber dashboard, and none of the links would work anymore (given the above error).  The simple workout is that I change the http to https in the page source, and the links worked again.  Eventually, the whitelist caught up again and I was allowed to log into the Eco server again.

The action attribute on the buttons should always be set to https I suppose.

**Comment by GoryMoon** [comment]
Thanks for the report, I will look into this.

**Comment by GoryMoon** [comment]
This should be fixed now.
