### ISSUE TITLE
Link/Unlink to whitelist button for Steam account doesn't work anymore

### ISSUE THREAD

**Issue by Fireztonez** [GoryMoon/SubscriptionWhitelist#16]
Hello,
I have an Eco sub-server setup with with your mod, the mod still refresh the whitelist each 5 minutes and everything work's on that side, but new subs can't Link is Steam to the Subscriber whitelist. The user is still able to link is Steam Account with is Twitch account, but the button Link/Unlink seam to not work anymore

![image](https://user-images.githubusercontent.com/19277301/96317884-ff935700-0fdc-11eb-9d5f-a1aee53e574a.png)

One of my sub report me this issue, he have try on Chrome, Opera and Ms. Edge and doesn't work. I tried myself on Vivaldi (How tried myself before and it work well) and Firefox, doesn't work anymore.

So right now I have to add manually Steam ID, so this break totally the purpose of your mod right now.

**Comment by GoryMoon** [comment]
Will take a look into this.

**Comment by GoryMoon** [comment]
Can you have a look again, I think this is a duplicate of #15 that I fixed from my testing.

**Comment by Fireztonez** [comment]
Perfect, I just try and the "Link Steam to Whitelist" button work great now. Thank's.

I look the other issue before writing my message, I didn't think it was a duplicate, but it is quite possible. My English is not excellent and his problem was written in such a technical way that I had difficulty understanding, despite my computer and development knowledge.

Thank's

**Comment by GoryMoon** [comment]
Yeah, no worries.
It wasn't until I started to look at it that I figure they were related.
