### ISSUE TITLE
New subs not adding to whitelist

### ISSUE THREAD

**Issue by tonacho69** [GoryMoon/SubscriptionWhitelist#27]
Hi!
My new twitch subs are getting an error while adding the channel. The error is "You are not subscribed to this channel, you can not add to its whitelist" besides they are subscribed.
I deleted and readded the twitch connection but it not worked.
Thank you for your time.

**Comment by tonacho69** [comment]
I'm sorry, my channel is twitch.tv/tonacho
thank you!

**Comment by Darkosto** [comment]
Same issue happening here. Can't add any new subs to the list

**Comment by GoryMoon** [comment]
I think I've resolved the issue now, sorry for the delay with looking into and fixing this.
